from ad_set_insight.models import AdSetInsight
from rest_framework import serializers

class AdSetInsightSerializer(serializers.ModelSerializer):
    class Meta:
        model = AdSetInsight
        fields = ('account_id',
                'actions',
                'ad_id',
                'adset_id',
                'call_to_action_clicks',
                'campaign_id',
                'canvas_avg_view_percent',
                'canvas_avg_view_time',
                'clicks',
                'cost_per_10_sec_video_view',
                'cost_per_action_type',
                'cost_per_estimated_ad_recallers',
                'cost_per_inline_link_click',
                'cost_per_inline_post_engagement',
                'cost_per_outbound_click',
                'cost_per_total_action',
                'cost_per_unique_action_type',
                'cost_per_unique_click',
                'cost_per_unique_inline_link_click',
                'cost_per_unique_outbound_click',
                'cpc',
                'cpm',
                'cpp',
                'ctr',
                'date_start',
                'date_stop',
                'estimated_ad_recall_rate',
                'frequency',
                'impressions',
                'inline_link_click_ctr',
                'inline_link_clicks',
                'inline_post_engagement',
                'objective',
                'outbound_clicks',
                'outbound_clicks_ctr',
                'reach',
                'social_clicks',
                'social_impressions',
                'social_reach',
                'social_spend',
                'spend',
                'total_action_value',
                'total_actions',
                'total_unique_actions',
                'unique_actions',
                'unique_clicks',
                'unique_ctr',
                'unique_inline_link_click_ctr',
                'unique_inline_link_clicks',
                'unique_link_clicks_ctr',
                'unique_outbound_clicks',
                'unique_outbound_clicks_ctr',
                'unique_social_clicks',
                'video_10_sec_watched_actions',
                # 'video_15_sec_watched_actions',
                'video_30_sec_watched_actions',
                'video_avg_percent_watched_actions',
                'video_avg_time_watched_actions',
                'video_p100_watched_actions',
                'video_p25_watched_actions',
                'video_p50_watched_actions',
                'video_p75_watched_actions',
                'video_p95_watched_actions',
                'website_ctr')
