# Generated by Django 2.0 on 2017-12-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fb_ad_account', '0002_auto_20171226_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=64)),
                ('updated_by', models.CharField(max_length=64)),
                ('neo_adv_id', models.IntegerField()),
                ('neo_accouint_id', models.IntegerField()),
                ('fb_ad_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fb_ad_account.FbAdAccount')),
            ],
            options={
                'db_table': 'neo_accounts',
            },
        ),
    ]
