# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neoaccount',
            old_name='neo_accouint_id',
            new_name='neo_account_id',
        ),
    ]
