# Generated by Django 2.0 on 2017-12-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pixel_mapping', '0001_initial'),
        ('fb_ad_account', '0002_auto_20171226_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickdataAccountTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=64)),
                ('updated_by', models.CharField(max_length=64)),
                ('target_audience_id', models.BigIntegerField()),
                ('rentention_days', models.IntegerField()),
                ('target_status', models.IntegerField()),
                ('extra_pixel_mapping', models.IntegerField(null=True)),
                ('fb_ad_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fb_ad_account.FbAdAccount')),
                ('pixel_mapping', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='pixel_mapping.PixelMapping')),
            ],
            options={
                'db_table': 'pickdata_account_targets',
            },
        ),
    ]
