# Generated by Django 2.0 on 2017-12-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickdata_account_target', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickdataaccounttarget',
            old_name='extra_pixel_mapping',
            new_name='extra_pixel_mapping_id',
        ),
    ]
