# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_mapping_category', '0001_initial'),
        ('pickdata_account_target', '0003_auto_20180109_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickdataaccounttarget',
            name='pixel_mapping',
        ),
        migrations.AddField(
            model_name='pickdataaccounttarget',
            name='pixel_mapping_category',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='pixel_mapping_category.PixelMappingCategory'),
            preserve_default=False,
        ),
    ]
