# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_set_insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsetinsight',
            name='carousel_actions',
            field=models.TextField(null=True),
        ),
    ]
