# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_set_insight', '0002_adsetinsight_carousel_actions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adsetinsight',
            unique_together=set([('adset_id', 'date_start', 'date_stop')]),
        ),
    ]
