# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=64)),
                ('updated_by', models.CharField(max_length=64)),
                ('account_id', models.CharField(max_length=64)),
                ('account_name', models.CharField(max_length=256)),
                ('campaign_id', models.CharField(max_length=64)),
                ('campaign_name', models.CharField(max_length=256)),
                ('campaign_objective', models.CharField(max_length=64)),
                ('adset_id', models.CharField(max_length=64, unique=True)),
                ('adset_name', models.CharField(max_length=256)),
                ('daily_budget', models.CharField(max_length=64)),
                ('lifetime_budget', models.CharField(max_length=64)),
                ('age_min', models.CharField(max_length=8)),
                ('age_max', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=8)),
                ('targeting', models.TextField()),
                ('include_interests', models.TextField(null=True)),
                ('include_behaviors', models.TextField(null=True)),
                ('exclude_interests', models.TextField(null=True)),
                ('exclude_behaviors', models.TextField(null=True)),
                ('custom_audiences', models.TextField(null=True)),
                ('excluded_custom_audiences', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ad_sets',
            },
        ),
    ]
