# Generated by Django 2.0 on 2017-12-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fb_ad_account', '0002_auto_20171226_1229'),
        ('pixel_mapping_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=64)),
                ('updated_by', models.CharField(max_length=64)),
                ('facebook_pixel_event_name', models.CharField(max_length=128)),
                ('fb_ad_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fb_ad_account.FbAdAccount')),
                ('pixel_mapping_category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='pixel_mapping_category.PixelMappingCategory')),
            ],
            options={
                'db_table': 'pixel_mappings',
            },
        ),
    ]
