# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelmapping',
            name='facebook_pixel_event_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
