# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_mapping_category', '0001_initial'),
        ('fb_ad_account', '0005_auto_20180112_1707'),
        ('pixel_mapping', '0002_auto_20180116_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pixelmapping',
            unique_together=set([('fb_ad_account', 'facebook_pixel_event_name', 'pixel_mapping_category')]),
        ),
    ]
