# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fb_ad_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPixelMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=64)),
                ('updated_by', models.CharField(max_length=64)),
                ('event_mapping_name', models.CharField(max_length=128)),
                ('pixel_event_name', models.CharField(max_length=128)),
                ('fb_ad_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fb_ad_account.FbAdAccount')),
            ],
            options={
                'db_table': 'account_piexel_mappings',
            },
        ),
    ]
