# Generated by Django 2.0 on 2017-12-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixelMappingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=64)),
                ('updated_by', models.CharField(max_length=64)),
                ('category_label_kr', models.CharField(max_length=128)),
                ('category_label_en', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'pixel_mapping_category',
            },
        ),
    ]
