# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_ad_account', '0002_auto_20171226_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbadaccount',
            name='account_category',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_category.AccountCategory'),
        ),
        migrations.AlterField(
            model_name='fbadaccount',
            name='ad_account_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
