# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_ad_account', '0003_auto_20180111_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbadaccount',
            name='act_account_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='fbadaccount',
            name='ad_account_id',
            field=models.BigIntegerField(),
        ),
    ]
