# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_ad_account', '0004_auto_20180111_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbadaccount',
            name='account_category',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='account_category.AccountCategory'),
            preserve_default=False,
        ),
    ]
