# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_ad_account', '0005_auto_20180112_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbadaccount',
            name='default_pixel_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
