# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_ad_account', '0006_fbadaccount_default_pixel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbadaccount',
            old_name='default_pixel_id',
            new_name='pixel_id',
        ),
    ]
